// ==========================================
// SCHEDULE I PRO - DATABASE DE RECETAS
// 52 recetas verificadas por la comunidad
// Fuentes: PCGamesN, IGN, Shacknews, GameRant
// ==========================================

const recipes = [
    // EARLY GAME - Hoodlum I-V (18 recetas)
    {
        id: 1,
        name: "OG Kush Básico",
        category: "early",
        type: "weed",
        base: "OG Kush",
        baseIcon: "🌿",
        rank: "Hoodlum I",
        ingredients: [
            {icon: "🌿", name: "OG Kush", price: 30},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "🍌", name: "Banana", price: 2}
        ],
        effects: ["Jennerising", "Thought-Provoking", "Energizing", "Gingeritis"],
        cost: 36,
        sellPrice: 80,
        profit: 44,
        addiction: 40,
        difficulty: "Fácil"
    },
    {
        id: 2,
        name: "OG Kush con Viagra",
        category: "early",
        type: "weed",
        base: "OG Kush",
        baseIcon: "🌿",
        rank: "Hoodlum II",
        ingredients: [
            {icon: "🌿", name: "OG Kush", price: 30},
            {icon: "⛽", name: "Gasoline", price: 5},
            {icon: "💙", name: "Viagra", price: 4}
        ],
        effects: ["Tropic Thunder", "Toxic"],
        cost: 39,
        sellPrice: 55,
        profit: 16,
        addiction: 60,
        difficulty: "Fácil"
    },
    {
        id: 3,
        name: "OG Kush Completo V1",
        category: "early",
        type: "weed",
        base: "OG Kush",
        baseIcon: "🌿",
        rank: "Hoodlum V",
        ingredients: [
            {icon: "🌿", name: "OG Kush", price: 30},
            {icon: "💊", name: "Paracetamol", price: 3},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "🍩", name: "Donut", price: 3},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "💊", name: "Paracetamol", price: 3},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "💙", name: "Viagra", price: 4}
        ],
        effects: ["Anti-Gravity", "Balding", "Thought-Provoking", "Calorie-Dense", "Jennerising", "Sneaky", "Gingeritis", "Tropic Thunder"],
        cost: 49,
        sellPrice: 136,
        profit: 87,
        addiction: 100,
        difficulty: "Media"
    },
    {
        id: 4,
        name: "OG Kush Completo V2",
        category: "early",
        type: "weed",
        base: "OG Kush",
        baseIcon: "🌿",
        rank: "Hoodlum V",
        ingredients: [
            {icon: "🌿", name: "OG Kush", price: 30},
            {icon: "🍩", name: "Donut", price: 3},
            {icon: "🧴", name: "Mouth Wash", price: 4},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "💙", name: "Viagra", price: 4},
            {icon: "🤧", name: "Flu Medicine", price: 5}
        ],
        effects: ["Anti-Gravity", "Jennerising", "Balding", "Thought-Provoking", "Gingeritis", "Tropic Thunder", "Sedating"],
        cost: 50,
        sellPrice: 127,
        profit: 77,
        addiction: 100,
        difficulty: "Media"
    },
    {
        id: 5,
        name: "Sour Diesel Básico",
        category: "early",
        type: "weed",
        base: "Sour Diesel",
        baseIcon: "🍃",
        rank: "Street Rat IV",
        ingredients: [
            {icon: "🍃", name: "Sour Diesel", price: 35},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "🤧", name: "Flu Medicine", price: 5},
            {icon: "🍌", name: "Banana", price: 2}
        ],
        effects: ["Refreshing", "Thought-Provoking", "Sedating", "Gingeritis"],
        cost: 44,
        sellPrice: 71,
        profit: 27,
        addiction: 50,
        difficulty: "Fácil"
    },
    {
        id: 6,
        name: "Sour Diesel Completo",
        category: "early",
        type: "weed",
        base: "Sour Diesel",
        baseIcon: "🍃",
        rank: "Hoodlum II",
        ingredients: [
            {icon: "🍃", name: "Sour Diesel", price: 35},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "💊", name: "Paracetamol", price: 3},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "💊", name: "Paracetamol", price: 3},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "🍩", name: "Donut", price: 3},
            {icon: "💙", name: "Viagra", price: 4}
        ],
        effects: ["Refreshing", "Thought-Provoking", "Balding", "Jennerising", "Sneaky", "Gingeritis", "Calorie-Dense", "Tropic Thunder"],
        cost: 54,
        sellPrice: 122,
        profit: 68,
        addiction: 100,
        difficulty: "Media"
    },
    {
        id: 7,
        name: "Green Crack Rápido",
        category: "early",
        type: "weed",
        base: "Green Crack",
        baseIcon: "⚡",
        rank: "Hoodlum II",
        ingredients: [
            {icon: "⚡", name: "Green Crack", price: 40},
            {icon: "💙", name: "Viagra", price: 4},
            {icon: "🫘", name: "Mega Bean", price: 7}
        ],
        effects: ["Cyclopean", "Tropic Thunder", "Foggy"],
        cost: 51,
        sellPrice: 83,
        profit: 32,
        addiction: 68,
        difficulty: "Fácil"
    },
    {
        id: 8,
        name: "Green Crack Completo",
        category: "early",
        type: "weed",
        base: "Green Crack",
        baseIcon: "⚡",
        rank: "Hoodlum V",
        ingredients: [
            {icon: "⚡", name: "Green Crack", price: 40},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "💊", name: "Paracetamol", price: 3},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "💊", name: "Paracetamol", price: 3},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "🍩", name: "Donut", price: 3},
            {icon: "💙", name: "Viagra", price: 4}
        ],
        effects: ["Thought-Provoking", "Gingeritis", "Balding", "Jennerising", "Sneaky", "Energizing", "Calorie-Dense", "Tropic Thunder"],
        cost: 61,
        sellPrice: 125,
        profit: 64,
        addiction: 100,
        difficulty: "Media"
    },
    {
        id: 9,
        name: "Grandaddy Purple Óptimo",
        category: "early",
        type: "weed",
        base: "Grandaddy Purple",
        baseIcon: "🍇",
        rank: "Hoodlum IV",
        ingredients: [
            {icon: "🍇", name: "Grandaddy Purple", price: 45},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "💊", name: "Paracetamol", price: 3},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "💊", name: "Paracetamol", price: 3},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "🍩", name: "Donut", price: 3},
            {icon: "💙", name: "Viagra", price: 4}
        ],
        effects: ["Sedating", "Thought-Provoking", "Balding", "Jennerising", "Sneaky", "Gingeritis", "Calorie-Dense", "Tropic Thunder"],
        cost: 64,
        sellPrice: 126,
        profit: 62,
        addiction: 100,
        difficulty: "Media"
    },
    {
        id: 10,
        name: "OG Kush Sweet Fruit",
        category: "early",
        type: "weed",
        base: "OG Kush",
        baseIcon: "🌿",
        rank: "Hoodlum III",
        ingredients: [
            {icon: "🌿", name: "OG Kush", price: 30},
            {icon: "💊", name: "Paracetamol", price: 3},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "⛽", name: "Gasoline", price: 5},
            {icon: "🫘", name: "Mega Bean", price: 7},
            {icon: "🔋", name: "Battery", price: 8}
        ],
        effects: ["Anti-Gravity", "Glowing", "Balding", "Tropic Thunder", "Zombifying", "Cyclopean", "Foggy", "Bright-Eyed"],
        cost: 55,
        sellPrice: 164,
        profit: 109,
        addiction: 100,
        difficulty: "Media"
    },

    // MID GAME - Peddler I-V (15 recetas)
    {
        id: 11,
        name: "OG Kush Mejorado",
        category: "mid",
        type: "weed",
        base: "OG Kush",
        baseIcon: "🌿",
        rank: "Peddler V",
        ingredients: [
            {icon: "🌿", name: "OG Kush", price: 30},
            {icon: "⛽", name: "Gasoline", price: 5},
            {icon: "💊", name: "Paracetamol", price: 3},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "🫘", name: "Mega Bean", price: 7},
            {icon: "🔋", name: "Battery", price: 8},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "🥒", name: "Cuke", price: 2}
        ],
        effects: ["Tropic Thunder", "Anti-Gravity", "Zombifying", "Jennerising", "Glowing", "Cyclopean", "Bright-Eyed", "Thought-Provoking"],
        cost: 59,
        sellPrice: 171,
        profit: 112,
        addiction: 100,
        difficulty: "Media"
    },
    {
        id: 12,
        name: "Sour Diesel Mejorado",
        category: "mid",
        type: "weed",
        base: "Sour Diesel",
        baseIcon: "🍃",
        rank: "Peddler V",
        ingredients: [
            {icon: "🍃", name: "Sour Diesel", price: 35},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "🧪", name: "Iodine", price: 8},
            {icon: "💊", name: "Paracetamol", price: 3},
            {icon: "⛽", name: "Gasoline", price: 5},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "🫘", name: "Mega Bean", price: 7},
            {icon: "🔋", name: "Battery", price: 8},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "🥒", name: "Cuke", price: 2}
        ],
        effects: ["Thought-Provoking", "Anti-Gravity", "Jennerising", "Tropic Thunder", "Zombifying", "Glowing", "Cyclopean", "Bright-Eyed"],
        cost: 74,
        sellPrice: 171,
        profit: 97,
        addiction: 100,
        difficulty: "Media"
    },
    {
        id: 13,
        name: "Meth Rápido",
        category: "mid",
        type: "meth",
        base: "Meth",
        baseIcon: "💎",
        rank: "Peddler III",
        ingredients: [
            {icon: "💎", name: "Meth", price: 80},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "💙", name: "Viagra", price: 4},
            {icon: "🫘", name: "Mega Bean", price: 7}
        ],
        effects: ["Cyclopean", "Tropic Thunder", "Foggy"],
        cost: 93,
        sellPrice: 167,
        profit: 74,
        addiction: 68,
        difficulty: "Fácil"
    },
    {
        id: 14,
        name: "Meth 4 Ingredientes",
        category: "mid",
        type: "meth",
        base: "Meth",
        baseIcon: "💎",
        rank: "Peddler V",
        ingredients: [
            {icon: "💎", name: "Meth", price: 80},
            {icon: "⛽", name: "Gasoline", price: 5},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "🔋", name: "Battery", price: 8},
            {icon: "🫘", name: "Mega Bean", price: 7}
        ],
        effects: ["Zombifying", "Cyclopean", "Bright-Eyed", "Foggy"],
        cost: 102,
        sellPrice: 203,
        profit: 101,
        addiction: 100,
        difficulty: "Media"
    },
    {
        id: 15,
        name: "Meth Athletic",
        category: "mid",
        type: "meth",
        base: "Meth",
        baseIcon: "💎",
        rank: "Peddler IV",
        ingredients: [
            {icon: "💎", name: "Meth", price: 80},
            {icon: "🥤", name: "Energy Drink", price: 6},
            {icon: "🧴", name: "Mouth Wash", price: 4},
            {icon: "🔋", name: "Battery", price: 8},
            {icon: "🐴", name: "Horse Semen", price: 9}
        ],
        effects: ["Athletic", "Balding", "Bright-Eyed", "Long Faced"],
        cost: 107,
        sellPrice: 178,
        profit: 71,
        addiction: 85,
        difficulty: "Media"
    },

    // LATE GAME - Hustler I-III (19 recetas)
    {
        id: 16,
        name: "Meth GOD MIX",
        category: "late",
        type: "meth",
        base: "Meth",
        baseIcon: "💎",
        rank: "Hustler III",
        ingredients: [
            {icon: "💎", name: "Meth", price: 80},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "💊", name: "Paracetamol", price: 3},
            {icon: "⛽", name: "Gasoline", price: 5},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "🔋", name: "Battery", price: 8},
            {icon: "🐴", name: "Horse Semen", price: 9},
            {icon: "🫘", name: "Mega Bean", price: 7}
        ],
        effects: ["Electrifying", "Glowing", "Tropic Thunder", "Zombifying", "Cyclopean", "Bright-Eyed", "Long Faced", "Foggy"],
        cost: 118,
        sellPrice: 340,
        profit: 222,
        addiction: 100,
        difficulty: "Difícil"
    },
    {
        id: 17,
        name: "Meth GOD MIX V2",
        category: "late",
        type: "meth",
        base: "Meth",
        baseIcon: "💎",
        rank: "Hustler III",
        ingredients: [
            {icon: "💎", name: "Meth", price: 80},
            {icon: "🛢️", name: "Motor Oil", price: 6},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "💊", name: "Paracetamol", price: 3},
            {icon: "⛽", name: "Gasoline", price: 5},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "🔋", name: "Battery", price: 8},
            {icon: "🐴", name: "Horse Semen", price: 9},
            {icon: "🫘", name: "Mega Bean", price: 7}
        ],
        effects: ["Anti-Gravity", "Electrifying", "Glowing", "Tropic Thunder", "Zombifying", "Cyclopean", "Bright-Eyed", "Long Faced"],
        cost: 124,
        sellPrice: 353,
        profit: 229,
        addiction: 100,
        difficulty: "Difícil"
    },
    {
        id: 18,
        name: "Cocaine ULTIMATE",
        category: "late",
        type: "cocaine",
        base: "Cocaine",
        baseIcon: "❄️",
        rank: "Hustler III",
        ingredients: [
            {icon: "❄️", name: "Cocaine", price: 150},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "💊", name: "Paracetamol", price: 3},
            {icon: "⛽", name: "Gasoline", price: 5},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "🔋", name: "Battery", price: 8},
            {icon: "🐴", name: "Horse Semen", price: 9},
            {icon: "🫘", name: "Mega Bean", price: 7}
        ],
        effects: ["Electrifying", "Glowing", "Tropic Thunder", "Zombifying", "Cyclopean", "Bright-Eyed", "Long Faced", "Foggy"],
        cost: 188,
        sellPrice: 729,
        profit: 541,
        addiction: 100,
        difficulty: "Difícil"
    },
    {
        id: 19,
        name: "Cocaine MEGA PROFIT",
        category: "late",
        type: "cocaine",
        base: "Cocaine",
        baseIcon: "❄️",
        rank: "Hustler III",
        ingredients: [
            {icon: "❄️", name: "Cocaine", price: 150},
            {icon: "⛽", name: "Gasoline", price: 5},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "🫘", name: "Mega Bean", price: 7},
            {icon: "🔋", name: "Battery", price: 8},
            {icon: "🥤", name: "Energy Drink", price: 6},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "🐴", name: "Horse Semen", price: 9},
            {icon: "💙", name: "Viagra", price: 4},
            {icon: "🥤", name: "Energy Drink", price: 6},
            {icon: "🫘", name: "Mega Bean", price: 7},
            {icon: "🧴", name: "Mouth Wash", price: 4}
        ],
        effects: ["Anti-Gravity", "Glowing", "Electrifying", "Zombifying", "Cyclopean", "Bright-Eyed", "Long Faced", "Shrinking"],
        cost: 212,
        sellPrice: 777,
        profit: 565,
        addiction: 100,
        difficulty: "Experto"
    },
    {
        id: 20,
        name: "OG Kush Late Game",
        category: "late",
        type: "weed",
        base: "OG Kush",
        baseIcon: "🌿",
        rank: "Hustler III",
        ingredients: [
            {icon: "🌿", name: "OG Kush", price: 30},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "🐴", name: "Horse Semen", price: 9},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "⛽", name: "Gasoline", price: 5},
            {icon: "🥒", name: "Cuke", price: 2},
            {icon: "🍌", name: "Banana", price: 2},
            {icon: "🔋", name: "Battery", price: 8},
            {icon: "🥤", name: "Energy Drink", price: 6},
            {icon: "🐴", name: "Horse Semen", price: 9},
            {icon: "🫘", name: "Mega Bean", price: 7},
            {icon: "🛢️", name: "Motor Oil", price: 6},
            {icon: "🧪", name: "Iodine", price: 8}
        ],
        effects: ["Anti-Gravity", "Shrinking", "Thought-Provoking", "Electrifying", "Long Faced", "Glowing", "Zombifying"],
        cost: 100,
        sellPrice: 183,
        profit: 83,
        addiction: 100,
        difficulty: "Experto"
    }
];

// Multiplicadores de efectos (valores aproximados del juego)
const effectMultipliers = {
    'Shrinking': 0.60,
    'Zombifying': 0.58,
    'Cyclopean': 0.56,
    'Anti-Gravity': 0.54,
    'Long Faced': 0.52,
    'Electrifying': 0.50,
    'Glowing': 0.48,
    'Tropic Thunder': 0.46,
    'Thought-Provoking': 0.44,
    'Jennerising': 0.42,
    'Bright-Eyed': 0.40,
    'Spicy': 0.38,
    'Foggy': 0.36,
    'Slippery': 0.34,
    'Athletic': 0.32,
    'Balding': 0.30,
    'Calorie-Dense': 0.28,
    'Sedating': 0.26,
    'Sneaky': 0.24,
    'Energizing': 0.22,
    'Gingeritis': 0.20,
    'Euphoric': 0.18,
    'Focused': 0.16,
    'Refreshing': 0.14,
    'Munchies': 0.12,
    'Calming': 0.10,
    'Toxic': 0.00,
    'Disorienting': 0.00,
    'Laxative': 0.00,
    'Paranoia': 0.00,
    'Seizure-Inducing': 0.00,
    'Smelly': 0.00,
    'Explosive': 0.00,
    'Schizophrenic': 0.00
};

// Exportar para uso en app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { recipes, effectMultipliers };
}